name: dongfang_face_client
description: 东方仙盟人脸识别控制端
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  # 调用Rust API
  json_annotation: ^4.8.1  # JSON序列化
  url_launcher: ^6.2.2  # 打开API文档
  flutter_spinkit: ^5.2.0  # 加载动画

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png  # 可自行添加logo
